@host=http://localhost:8282
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1Nzc1MWZhZi0zOWUxLTRiOGEtYmRmNi1lN2Y3NjZhZmFjYjkiLCJnaXZlbl9uYW1lIjoiSm9obiIsImZhbWlseV9uYW1lIjoiQnJvd24iLCJqdGkiOiIzYTljZTM4YS1iNzVkLTQ1MjgtOWE1YS1mNzZkNTQyYjNjMDciLCJleHAiOjE3MTUwMzcwOTUsImlzcyI6IkJ1YmVyRGlubmVyIiwiYXVkIjoiQnViZXJEaW5uZXIifQ.UZ7DwjOJGOW3dnq8i5hD6AiGr1P7RVOIlTsMd-FB4cY
GET {{host}}/dinners
Authorization: Bearer {{token}}