$BD.Api_HostAddress = http://localhost:8181

POST {{$BD.Api_HostAddress}}/auth/register/
Content-Type: application/json

{ 
  "firstName":"Anton",
  "lastName":"Baksheiev",
  "email": "anton.baksheiev@gmai.com",
  "password":"Anton1242!"

}