@host=http://localhost:8282

POST {{host}}/auth/register/
Content-Type: application/json

{ 
  "firstName":"Anton",
  "lastName":"Baksheiev",
  "email": "firstname.lastname@gmai.com",
  "password":"first456last123"
}